Resolve "Web FTP"
alpacax/alpamon pull request #2
Opened 2024-10-21 04:44 UTC by Apdul0329

As mentioned in https://github.com/alpacanetworks/alpamon-go/issues/1, the following changes have been made to natively replace the FTP function with AIP:

- Implement FTPClient
   - An FTPClient has been implemented to establish a Control Connection with alpacon-server.
   - FTPClient receives Web FTP Commands, which map to FTP Commands, from the user and processes them.

FTP Command | Web FTP Command
-- | --
LIST | list
MKD | mkd
CWD | cwd
PWD | pwd
DELE | dele
RMD | rmd
RNFR/RNTO | mv
Not Defined | cp

- `openftp` Command Addition
   - `openftp` Command runs `FTPClient` as go routine.
   - `openftp` command integrate into the `CommandRunner`.

- Update upload & download alpamon Command
   - Web FTP provides FTP's Data Connection-like functionality through a REST API.
   - The upload and download commands support the following features.
      - bulk upload/download
      - recursive upload/download
      - zip upload
      - unzip download

Closes #1

2024-10-21 04:59 UTC, royroyee commented
Please fix all issues flagged by lint

2024-10-21 05:40 UTC, royroyee commented
The current code heavily uses `map[string]interface{}`, leading to frequent type assertions. In Go, it’s better to define explicit structs for type safety and to reduce conversions.

For request/response types, using **omitempty** can simplify things.

Since invalid type assertions cause a panic in Go, it’s safer to use:

```go
size, ok := result["size"].(int64)
```

Alternatively, you can use a switch statement to determine the type beforehand:
```go
switch v := addr.(type) {
case *net.IPNet:
    ...
}
```

2024-10-22 05:11 UTC, Apdul0329 commented
Based on your feedback, I've refactored the code and conducted additional testing in a Linux environment. Please let me know if you have any further comments or if you would like me to make any additional changes.

2024-10-22 05:15 UTC, royroyee requested changes

2024-10-22 05:15 UTC, royroyee commented on pkg/runner/ftp.go
> +	ftpTerminals = make(map[string]*FtpClient)
A global variable `terminals` was added in pty for `session_id` reference due to resize, but if FTP doesn’t require this, please remove the global variable

2024-10-22 05:15 UTC, royroyee commented on pkg/runner/command.go
> +		defer os.Remove(name)
Ensure errors are handled explicitly when using defer (Go convention). Review and fix other areas as needed
```go	
	defer func() { _ = os.Remove(name) }()
```

2024-10-22 05:15 UTC, royroyee commented on pkg/runner/command.go
> +func parsePaths(pathList []string) ([]string, bool, bool, error) {
Consider adding descriptive names for return values to improve readability, especially when there are multiple return variables in Go. For example:
```go
func (cr *CommandRunner) delGroup() (exitCode int, result string) {

```

2024-10-22 05:15 UTC, royroyee commented on pkg/runner/ftp_types.go
> +var returnCodes = map[string]returnCode{
It’s better to use const for the error messages rather than repeating them:
```go
const (
    ErrPermissionDenied = "permission denied"
    ErrInvalidArgument  = "invalid argument"
    ErrNoSuchFile       = "no such file or directory"
    ...
    )
```
Additionally, instead of returning `map[string]string`, it would be clearer to define a specific type for the return value.

2024-10-22 05:28 UTC, royroyee requested changes

2024-10-22 05:28 UTC, royroyee commented on pkg/runner/ftp_types.go
> +	Data    interface{} `json:"data,omitempty"`
Consider defining a specific type for the `data` field instead of using an interface. Please review

2024-10-22 05:57 UTC, royroyee commented
It looks like there are some []string types like ‘path’ that need validation for empty arrays. Accessing an empty array could cause a panic

2024-10-22 06:24 UTC, royroyee commented on scripts/postinstall.sh
> +    apt-get update
No update needed. it’s already included in the Linux package script

2024-10-22 08:38 UTC, geunwoonoh commented
I've addressed all the code review comments. Please review and resolve if everything looks good.

2024-10-23 04:34 UTC, Apdul0329 commented
I've made additional improvements to the makeArchive() for better readability.

2024-10-23 04:38 UTC, royroyee commented on pkg/runner/ftp_types.go
> +var returnCodes = map[string]returnCode{
Permissioned -> Permission

2024-10-23 04:43 UTC, Apdul0329 commented on pkg/runner/ftp_types.go
> +var returnCodes = map[string]returnCode{
I've fixed typo!

2024-10-23 05:01 UTC, royroyee commented on pkg/runner/ftp.go
> +	return *cmdResult, err
Remove unnecessary pointer dereferencing

2024-10-23 05:32 UTC, royroyee commented
LGTM~

2024-10-23 05:34 UTC, merged